version: '3'
services:
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass alex_rocks
    expose:
      - '6379'
    volumes:
      - ./.cache/redis:/data
    ports:
      - '6379:6379'
  database:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=kody
      - POSTGRES_PASSWORD=the_koala
      - POSTGRES_DB=kentcdodds_db
    ports:
      - '5432:5432'
